app:
  config:
    client:
      peerId: *********
    handler:
      numberOfAttempts: 3
      messageSenderTimeout: 2000
    scheduler:
      period: 500
      awaitTerminationMillis: 1000
      threadNamePrefix: bot-sch
    creeds:
      groupId: *********
      groupToken: vk1.a.*********************
